[package]
name = "apyxl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
chumsky = "1.0.0-alpha.0"
log = "0.4"
env_logger = "0.10"
